### ISSUE TITLE
pkg.json contains a package without a header.

### ISSUE THREAD

**Issue by flecheria** [teocomi/HelloDynamo#1]
Hi
I tryed to compile your project but i've got the following error message in DynamoBim console:

Exception encountered scanning the package directory at C:\Users\flecheria\AppData\Roaming\Dynamo\Dynamo Core\1.3\packages\HelloNodeModel
System.Exception:
A duplicate of the package called HelloNodeModel was found at C:\Users\flecheria\AppData\Roaming\Dynamo\Dynamo Core\1.3\packages\HelloNodeModel.  Ignoring it.
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory)
Exception encountered scanning the package directory at C:\Users\flecheria\AppData\Roaming\Dynamo\Dynamo Core\1.3\definitions
System.Exception:
C:\Users\flecheria\AppData\Roaming\Dynamo\Dynamo Core\1.3\definitions\pkg.json contains a package without a header.  Ignoring it.
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory)
Exception encountered scanning the package directory at C:\Users\flecheria\AppData\Roaming\Dynamo\Dynamo Core\1.3\Logs
System.Exception:
C:\Users\flecheria\AppData\Roaming\Dynamo\Dynamo Core\1.3\Logs\pkg.json contains a package without a header.  Ignoring it.
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory)
Exception encountered scanning the package directory at C:\Users\flecheria\AppData\Roaming\Dynamo\Dynamo Core\1.3\packages
System.Exception:
C:\Users\flecheria\AppData\Roaming\Dynamo\Dynamo Core\1.3\packages\pkg.json contains a package without a header.  Ignoring it.
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory)

Any hints?
Thanks
Paolo

Project is compile against VisualStudio 2015 - NET 4.5.2 and the compiled library are in C:\Users\flecheria\AppData\Roaming\Dynamo\Dynamo Core\1.3\packages\HelloNodeModel

**Comment by flecheria** [comment]
Solved. Wrong folder structure.
